service: lambda-file-uploader

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  main:
    handler: bin/main
    events:
      - http:
          path: /
          method: post